name: Auto Merge Owner

on:
  pull_request:
    types: [opened, reopened]

jobs:
  merge:
      runs-on: ubuntu-latest
      steps:
      - uses: managedkaos/merge-pull-request@v1.2
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION }}

